// packages/ui/src/react/components/ui/tabs.tsx
import * as React from "react"
import * as TabsPrimitive from "@radix-ui/react-tabs"

import { cn } from "@/lib/utils"

function Tabs({
  className,
  ...props
}: React.ComponentProps<typeof TabsPrimitive.Root>) {
  return (
    <TabsPrimitive.Root
      data-slot="tabs"
      className={cn("em:flex em:flex-col em:gap-2", className)}
      {...props}
    />
  )
}

function TabsList({
  className,
  ...props
}: React.ComponentProps<typeof TabsPrimitive.List>) {
  return (
    <TabsPrimitive.List
      data-slot="tabs-list"
      className={cn(
        "em:bg-muted em:text-muted-foreground em:inline-flex em:h-9 em:w-fit em:items-center em:justify-center em:rounded-lg em:p-[3px]",
        className
      )}
      {...props}
    />
  )
}

function TabsTrigger({
  className,
  ...props
}: React.ComponentProps<typeof TabsPrimitive.Trigger>) {
  return (
    <TabsPrimitive.Trigger
      data-slot="tabs-trigger"
      className={cn(
        "em:data-[state=active]:bg-background em:dark:data-[state=active]:text-foreground em:focus-visible:border-ring em:focus-visible:ring-ring/50 em:focus-visible:outline-ring em:dark:data-[state=active]:border-input em:dark:data-[state=active]:bg-input/30 em:text-foreground em:dark:text-muted-foreground em:inline-flex em:h-[calc(100%-1px)] em:flex-1 em:items-center em:justify-center em:gap-1.5 em:rounded-md em:border em:border-transparent em:px-2 em:py-1 em:text-sm em:font-medium em:whitespace-nowrap em:transition-[color,box-shadow] em:focus-visible:ring-[3px] em:focus-visible:outline-1 em:disabled:pointer-events-none em:disabled:opacity-50 em:data-[state=active]:shadow-sm em:[&_svg]:pointer-events-none em:[&_svg]:shrink-0 em:[&_svg:not([class*=size-])]:size-4",
        className
      )}
      {...props}
    />
  )
}

function TabsContent({
  className,
  ...props
}: React.ComponentProps<typeof TabsPrimitive.Content>) {
  return (
    <TabsPrimitive.Content
      data-slot="tabs-content"
      className={cn("em:flex-1 em:outline-none", className)}
      {...props}
    />
  )
}

export { Tabs, TabsList, TabsTrigger, TabsContent }

// packages/ui/src/components/ui/Tabs.svelte
<script lang="ts">
  import { createTabs, melt } from '@melt-ui/svelte';
  import type { Tab } from './types';

  /**
   * Array of tabs to display
   */
  export let tabs: Tab[] = [];

  /**
   * Currently active tab value
   */
  export let value: string;

  /**
   * Callback when tab changes
   */
  export let onChange: ((value: string) => void) | undefined = undefined;

  /**
   * Layout orientation (default: horizontal)
   */
  export let orientation: 'horizontal' | 'vertical' = 'horizontal';

  // Create Melt UI tabs with controlled value
  const {
    elements: { root, list, trigger },
    states: { value: meltValue }
  } = createTabs({
    defaultValue: value,
    orientation,
    onValueChange: ({ next }) => {
      if (next && onChange) {
        onChange(next);
      }
      return next;
    }
  });

  // Sync external value prop with internal Melt state
  $: if (value !== undefined && value !== $meltValue) {
    meltValue.set(value);
  }
</script>

<div use:melt={$root}>
  <!-- Tab List (Navigation) -->
  <nav
    use:melt={$list}
    class="em-flex em-gap-1"
    class:em-flex-col={orientation === 'vertical'}
  >
    {#each tabs as tab (tab.value)}
      {@const isActive = $meltValue === tab.value}
      <button
        use:melt={$trigger(tab.value)}
        disabled={tab.disabled}
        type="button"
        class="
          em-inline-flex
          em-items-center
          em-rounded-md
          em-border-b-2
          em-border-transparent
          em-bg-transparent
          em-px-3
          em-py-1.5
          em-text-sm
          em-font-medium
          em-text-[#656D76]
          em-transition-colors
          focus:em-outline-none
          focus:em-ring-2
          focus:em-ring-[#0969DA]
          focus:em-ring-offset-1
          disabled:em-cursor-not-allowed
          disabled:em-opacity-50
        "
        class:em-bg-[#F6F8FA]={isActive}
        class:em-border-[#0969DA]={isActive}
        class:em-text-[#1F2328]={isActive}
        class:hover:em-border-[#D0D7DE]={!isActive}
        class:hover:em-bg-[#F6F8FA]={!isActive}
        class:hover:em-text-[#1F2328]={!isActive}
      >
        {tab.label}
      </button>
    {/each}
  </nav>

  <!-- Tab Content Slot (rendered by parent) -->
  <slot />
</div>
