// packages/ui/src/react/components/FloatButton.tsx
import { useState, useEffect, useRef } from 'react';
import { useConfigStore } from '@/stores/useConfigStore';
import { useRulesStore } from '@/stores/useRulesStore';
import type { GlobalConfig } from '@error-mock/core';

const MARGIN = 20;
const BUTTON_SIZE = 56;

interface Position {
  x: number;
  y: number;
}

interface DragStart {
  x: number;
  y: number;
  time: number;
}

/**
 * Clamp position to viewport boundaries with margin
 */
function clampPosition({ x, y }: Position): Position {
  const maxX = Math.max(MARGIN, window.innerWidth - BUTTON_SIZE - MARGIN);
  const maxY = Math.max(MARGIN, window.innerHeight - BUTTON_SIZE - MARGIN);
  return {
    x: Math.min(Math.max(MARGIN, x), maxX),
    y: Math.min(Math.max(MARGIN, y), maxY),
  };
}

/**
 * Get default position from GlobalConfig position setting
 */
function getPositionFromConfig(pos: GlobalConfig['position']): Position {
  switch (pos) {
    case 'bottom-right':
      return {
        x: window.innerWidth - BUTTON_SIZE - MARGIN,
        y: window.innerHeight - BUTTON_SIZE - MARGIN,
      };
    case 'bottom-left':
      return { x: MARGIN, y: window.innerHeight - BUTTON_SIZE - MARGIN };
    case 'top-right':
      return { x: window.innerWidth - BUTTON_SIZE - MARGIN, y: MARGIN };
    case 'top-left':
      return { x: MARGIN, y: MARGIN };
  }
}

/**
 * Save position to localStorage
 */
function savePosition(x: number, y: number): void {
  try {
    localStorage.setItem('error-mock-float-button-pos', JSON.stringify({ x, y }));
  } catch (err) {
    console.warn('[ErrorMock] Failed to save button position:', err);
  }
}

export function FloatButton() {
  const { globalConfig, toggleModal } = useConfigStore();
  const activeMockCount = useRulesStore((state) => state.activeMockCount());

  const [position, setPosition] = useState<Position>({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const dragStartRef = useRef<DragStart>({ x: 0, y: 0, time: 0 });

  // Initialize position from localStorage or config
  useEffect(() => {
    const initPosition = () => {
      // Try to load from localStorage first
      try {
        const saved = localStorage.getItem('error-mock-float-button-pos');
        if (saved) {
          const pos = JSON.parse(saved) as Position;
          if (typeof pos.x === 'number' && typeof pos.y === 'number') {
            setPosition(clampPosition(pos));
            return;
          }
        }
      } catch (err) {
        console.warn('[ErrorMock] Failed to load button position:', err);
      }

      // Fallback to config position
      const defaultPos = getPositionFromConfig(globalConfig.position);
      setPosition(clampPosition(defaultPos));
    };

    initPosition();
  }, [globalConfig.position]);

  // Drag handlers using Pointer Events (supports touch and mouse)
  const handlePointerDown = (e: React.PointerEvent<HTMLButtonElement>) => {
    e.preventDefault();
    setIsDragging(true);

    dragStartRef.current = {
      x: e.clientX - position.x,
      y: e.clientY - position.y,
      time: Date.now(),
    };

    // Capture pointer events
    (e.target as HTMLElement).setPointerCapture(e.pointerId);
  };

  const handlePointerMove = (e: React.PointerEvent<HTMLButtonElement>) => {
    if (!isDragging) return;

    const newPos = {
      x: e.clientX - dragStartRef.current.x,
      y: e.clientY - dragStartRef.current.y,
    };

    setPosition(clampPosition(newPos));
  };

  const handlePointerUp = (e: React.PointerEvent<HTMLButtonElement>) => {
    if (!isDragging) return;

    setIsDragging(false);

    // Calculate movement distance and time
    const dist = Math.hypot(
      e.clientX - (position.x + dragStartRef.current.x),
      e.clientY - (position.y + dragStartRef.current.y)
    );
    const time = Date.now() - dragStartRef.current.time;

    // Click detection: <5px movement and <300ms duration
    if (dist < 5 && time < 300) {
      toggleModal();
    } else {
      // Save position after drag
      savePosition(position.x, position.y);
    }

    // Release pointer capture
    (e.target as HTMLElement).releasePointerCapture(e.pointerId);
  };

  // Keyboard support
  const handleKeyDown = (e: React.KeyboardEvent<HTMLButtonElement>) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      toggleModal();
    }
  };

  return (
    <button
      className="em:fixed em:z-[9999] em:touch-none em:top-0 em:left-0 em:bg-blue-600 em:text-white em:rounded-full em:w-14 em:h-14 em:shadow-lg em:flex em:items-center em:justify-center em:cursor-pointer hover:em:bg-blue-700 hover:em:scale-105 em:transition-transform em:duration-200 focus:em:outline-none focus:em:ring-2 focus:em:ring-offset-2 focus:em:ring-blue-500"
      style={{
        transform: `translate(${position.x}px, ${position.y}px)`,
        willChange: isDragging ? 'transform' : 'auto',
      }}
      onPointerDown={handlePointerDown}
      onPointerMove={handlePointerMove}
      onPointerUp={handlePointerUp}
      onKeyDown={handleKeyDown}
      role="button"
      aria-label="Toggle Error Mock Panel"
      tabIndex={0}
      type="button"
    >
      {/* Settings icon */}
      <svg
        className="em:h-8 em:w-8"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth="2"
          d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
        />
      </svg>

      {/* Active mock count badge */}
      {activeMockCount > 0 && (
        <span className="em:absolute -em:top-1 -em:right-1 em:bg-red-500 em:text-white em:text-xs em:font-bold em:w-6 em:h-6 em:rounded-full em:flex em:items-center em:justify-center em:border-2 em:border-white em:animate-pulse">
          {activeMockCount}
        </span>
      )}
    </button>
  );
}

// packages/ui/src/components/FloatButton.svelte
<script lang="ts">
  import { spring } from 'svelte/motion';
  import { onMount, onDestroy } from 'svelte';
  import { activeMockCount } from '../stores/rules';
  import { isModalOpen, globalConfig } from '../stores/config';

  const BUTTON_SIZE = 56;
  const MARGIN = 20;

  // Clamp position to keep button within viewport
  function clampPosition({ x, y }: { x: number; y: number }) {
    const maxX = Math.max(MARGIN, window.innerWidth - BUTTON_SIZE - MARGIN);
    const maxY = Math.max(MARGIN, window.innerHeight - BUTTON_SIZE - MARGIN);
    return {
      x: Math.min(Math.max(MARGIN, x), maxX),
      y: Math.min(Math.max(MARGIN, y), maxY),
    };
  }

  // Spring animation for smooth drag movement
  // Default to bottom-right (will be overridden by loadSavedPosition)
  let coords = spring(
    { x: typeof window !== 'undefined' ? window.innerWidth - 76 : 0, y: typeof window !== 'undefined' ? window.innerHeight - 76 : 0 },
    {
      stiffness: 0.1,
      damping: 0.25,
    }
  );

  // Drag state
  let isDragging = false;
  let startPos = { x: 0, y: 0 };
  let startTime = 0;

  // Initialize position from config or use default
  onMount(() => {
    const pos = clampPosition(getPositionFromConfig($globalConfig.position));
    coords.set(pos, { hard: true });
    loadSavedPosition();
  });

  function getPositionFromConfig(
    position: 'bottom-right' | 'bottom-left' | 'top-right' | 'top-left'
  ) {
    const margin = 20;
    const buttonSize = 56;

    switch (position) {
      case 'bottom-right':
        return {
          x: window.innerWidth - buttonSize - margin,
          y: window.innerHeight - buttonSize - margin,
        };
      case 'bottom-left':
        return { x: margin, y: window.innerHeight - buttonSize - margin };
      case 'top-right':
        return { x: window.innerWidth - buttonSize - margin, y: margin };
      case 'top-left':
        return { x: margin, y: margin };
    }
  }

  function loadSavedPosition() {
    try {
      const saved = localStorage.getItem('error-mock-button-position');
      if (saved) {
        const pos = JSON.parse(saved);
        const clamped = clampPosition(pos);
        coords.set(clamped, { hard: true });
      }
    } catch (err) {
      console.warn('Failed to load button position:', err);
    }
  }

  function savePosition(x: number, y: number) {
    try {
      const clamped = clampPosition({ x, y });
      coords.set(clamped, { hard: true });
      localStorage.setItem('error-mock-button-position', JSON.stringify(clamped));
    } catch (err) {
      console.warn('Failed to save button position:', err);
    }
  }

  function handleMouseDown(e: MouseEvent) {
    isDragging = true;
    startPos = { x: e.clientX, y: e.clientY };
    startTime = Date.now();

    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    e.preventDefault();
  }

  function handleMouseMove(e: MouseEvent) {
    if (!isDragging) return;

    const buttonSize = 56;
    const newX = Math.max(0, Math.min(e.clientX - buttonSize / 2, window.innerWidth - buttonSize));
    const newY = Math.max(0, Math.min(e.clientY - buttonSize / 2, window.innerHeight - buttonSize));

    coords.set({ x: newX, y: newY });
  }

  function handleMouseUp(e: MouseEvent) {
    window.removeEventListener('mousemove', handleMouseMove);
    window.removeEventListener('mouseup', handleMouseUp);

    if (!isDragging) return;
    isDragging = false;

    const dist = Math.hypot(e.clientX - startPos.x, e.clientY - startPos.y);
    const time = Date.now() - startTime;

    // Click detection: <5px movement and <300ms duration
    if (dist < 5 && time < 300) {
      toggleModal();
    } else {
      // Save position after drag
      savePosition($coords.x, $coords.y);
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      toggleModal();
    }
  }

  function toggleModal() {
    isModalOpen.update((v) => !v);
  }

  onDestroy(() => {
    window.removeEventListener('mousemove', handleMouseMove);
    window.removeEventListener('mouseup', handleMouseUp);
  });
</script>

<div
  class="em-fixed em-z-[9999] em-touch-none em-top-0 em-left-0"
  style="transform: translate({$coords.x}px, {$coords.y}px); will-change: transform;"
>
  <button
    class="em-bg-blue-600 em-text-white em-rounded-full em-w-14 em-h-14 em-shadow-lg em-flex em-items-center em-justify-center em-cursor-pointer hover:em-bg-blue-700 hover:em-scale-105 em-transition-transform em-duration-200 focus:em-outline-none focus:em-ring-2 focus:em-ring-offset-2 focus:em-ring-blue-500 em-relative"
    on:mousedown={handleMouseDown}
    on:keydown={handleKeyDown}
    aria-label="Open Error Mock Settings"
    tabindex="0"
    type="button"
  >
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="em-h-8 em-w-8"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor"
      aria-hidden="true"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4"
      />
    </svg>

    {#if $activeMockCount > 0}
      <span
        class="em-absolute -em-top-1 -em-right-1 em-bg-red-500 em-text-white em-text-xs em-font-bold em-w-6 em-h-6 em-rounded-full em-flex em-items-center em-justify-center em-border-2 em-border-white em-animate-pulse"
        aria-label="{$activeMockCount} active mocks"
      >
        {$activeMockCount}
      </span>
    {/if}
  </button>
</div>
